application.yml, application-test.yml 작성
f-lab-edu/ticket-booking pull request #14
Opened 2022-09-13 11:46 UTC by hsw0905

- .gitignore 추가사항 반영
- DB 사용을 위한 gradle JPA 의존성 추가, 기타 의존성 버전 설정
- application.properties -> application.yml 변경 (이유: 가독성, 계층 구조 설정)
- 테스트시 인메모리 DB 사용 목적으로 H2 DB 설정
- application.yml : Hikari Connection Pool 설정
- 기타 logging, redis, local, dev환경 : DB 선정 후 필요할때 설정 예정
- 테스트 : DB connection 확인 
- resolved :#5

2022-09-13 12:16 UTC, tbonelee commented on app/src/main/resources/application.yml
> +
```yml
  config:
    import:
      - "optional:secrets.yml"
```
키 spring 내부에 위에 코드로 작성한 밸류를 추가해주셔야 기존 secrets설정 파일 import를 유지시킬 수 있을 것 같습니다

2022-09-13 12:20 UTC, hsw0905 commented on app/src/main/resources/application.yml
> +
넵 반영하였습니다 !

2022-09-13 12:28 UTC, tbonelee requested changes
application-test.yml에도 비슷한 요청 코멘트 추가했습니다

2022-09-13 12:28 UTC, tbonelee commented on app/src/main/resources/application-test.yml
> +      ddl-auto: create
application.yml과 같은 맥락에서 아래와 같은 밸류가 추가되어야 할 것 같습니다.

```yml
  config:
    import:
      - "optional:secrets-test.yml"
```
(코멘트 추가하면 바로 알림 가는 줄 몰랐네요ㅜㅜ 이 요청도 같이 부탁드립니다)

2022-09-13 14:00 UTC, tbonelee approved these changes
LGTM

2022-09-13 14:00 UTC, merged

2022-09-14 12:24 UTC, f-lab-lyan commented on app/build.gradle
> +    runtimeOnly 'com.h2database:h2'
나중에 테스트 용으로 변경하도록 하죠.

2022-09-14 12:27 UTC, f-lab-lyan commented on app/src/main/resources/application-test.yml
> +      ddl-auto: create
`app/src/test/resources` 밑으로 가야하지 않을까요?